resources:
  jobs:
    ml_training_pipeline:
      name: ml-training-pipeline
      description: |
        Train, validate, and deploy ML model.
        Runs train → validate → deploy as a multi-task job.
      tasks:
        - task_key: train
          notebook_task:
            notebook_path: ../src/train.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
          environment_key: ml_env

        - task_key: validate
          depends_on:
            - task_key: train
          notebook_task:
            notebook_path: ../src/validate.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
          environment_key: ml_env

        - task_key: deploy
          depends_on:
            - task_key: validate
          notebook_task:
            notebook_path: ../src/deploy.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
          environment_key: ml_env

      environments:
        - environment_key: ml_env
          spec:
            client: "1"
            dependencies:
              - mlflow[databricks]>=2.10.0
              - scikit-learn>=1.3.0
              - pandas>=2.0.0
              - numpy>=1.24.0
              - databricks-sdk>=0.20.0
