resources:
  jobs:
    train_model:
      name: ml-model-training
      description: Train and register ML model with MLflow
      tasks:
        - task_key: feature_engineering
          notebook_task:
            notebook_path: ../src/feature_engineering.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
          job_cluster_key: ml_cluster

        - task_key: train
          depends_on:
            - task_key: feature_engineering
          notebook_task:
            notebook_path: ../src/train.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
              experiment_name: ${var.experiment_name}
          job_cluster_key: ml_cluster

        - task_key: register_model
          depends_on:
            - task_key: train
          notebook_task:
            notebook_path: ../src/register_model.py
            base_parameters:
              catalog: ${var.catalog}
              schema: ${var.schema}
              model_name: ${var.model_name}
          job_cluster_key: ml_cluster

      job_clusters:
        - job_cluster_key: ml_cluster
          new_cluster:
            spark_version: 14.3.x-cpu-ml-scala2.12
            num_workers: 2
            node_type_id: ${CLOUD_NODE_TYPE}
